# Generated by Django 5.1.7 on 2025-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_title_alter_product_title_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
