# Generated by Django 5.1.7 on 2025-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_contact_alter_setting_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reference',
            field=models.TextField(blank=True),
        ),
    ]
