# Generated by Django 5.1.7 on 2025-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_setting_aboutus_alter_setting_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
